import Header from '@/components/Home/Header';
import './globals.css';
import { Inter } from 'next/font/google';
import Footer from '@/components/Home/Footer';
import NextAuthProvider from './providers/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Header />
          {children}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}

export default RootLayout;